language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - 1
  - nightly
env:
  - JULIA_NUM_THREADS=2
matrix:
  allow_failures:
    - julia: nightly
after_success:
  - julia -e 'cd(Pkg.dir("FileIO")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
notifications:
  email: false
