name: Run tests

on:
  pull_request:
  push:
    branches:
      - master
    tags: '*'

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}

    permissions:
      actions: write
      contents: read
    
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'    # Current stable version
        os:
          - ubuntu-latest
          - windows-latest
        arch:
          - x64
        include:
          - os: macOS-latest
            arch: aarch64
            version: '1'
          - os: ubuntu-latest
            arch: x86
            version: '1'
          - os: ubuntu-latest
            arch: x64
            version: '1.6'
          - os: ubuntu-latest
            arch: x64
            version: 'nightly'
    steps:
      - name: Set git to use LF (Windows only)
        if: matrix.os == 'windows-latest'
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Fix TEMP issue (Windows only) # See https://github.com/actions/virtual-environments/issues/712
        if: matrix.os == 'windows-latest'
        run: |
          echo "TMP=${USERPROFILE}\AppData\Local\Temp" >> ${GITHUB_ENV}
          echo "TEMP=${USERPROFILE}\AppData\Local\Temp" >> ${GITHUB_ENV}
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          show-versioninfo: true
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-runtest@latest
        env:
          JULIA_NUM_THREADS: 2
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v4
        with:
          file: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
